name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  container-job:
    runs-on: ubuntu-latest
    container: golang:1.18-rc
    services:
        db:
          image: postgres:latest
          env:
            POSTGRES_DB: pbpgx_tester
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_USER: pbpgx_tester
          ports:
            - 5432:5432
          # set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
            
    steps:
    - uses: actions/checkout@v2
        
    - name: Download mods
      run: go mod download

    - name: Test
      run: go test -v -race -coverprofile=pbpgx.cov -covermode=atomic ./...

    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./pbpgx.cov
