name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    services:
        db:
          image: postgres:latest
          env:
            POSTGRES_DB: pbpgx_tester
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_USER: pbpgx_tester
          ports:
            - 5432:5432
          # set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
            
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: 14
        postgresql db: pbpgx_tester
        postgresql user: pbpgx_tester

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Set up Gotip
      run: go install golang.org/dl/gotip@latest && gotip download

    - name: Download mods
      run: gotip mod download

    - name: Test
      run: gotip test -v -race -coverprofile=bppgx.cov -covermode=atomic ./

    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./bppgx.cov
